"""Verify the seeded universe's identity against the live provider (M6b-1).

    python -m tools.verify_universe            # probes every seeded instrument
    python -m tools.verify_universe --instrument hdfc-bank

**What this checks, and what "verify" means here.** Not "does data exist" but *does the
data belong to the instrument we believe it does*. The seed states our claims; this tool
asks the vendor the same questions and records where the answers agree, disagree, or
cannot be corroborated at all. The direction matters: expectations come from the seed,
never from the vendor. A check whose expected value was generated by the thing under
test would always pass and would verify nothing.

**It is honest about its own limits.** The vendor cannot distinguish an ETF from an
equity (`NIFTYBEES` reports `EQUITY`), and returns no ISIN for ETFs — so those are
reported `uncorroborated`, not quietly passed. Where the seed claims no ISIN, the
vendor's value is recorded as a **candidate** awaiting authoritative confirmation
rather than adopted (doc 04's authoritative/candidate tiering).

**Live, deliberate, and never in CI** — the pattern M6b-0 established. A network call in
CI would forfeit the reproducibility guarantee everything else rests on (doc 11), so
this is a developer tool that writes a dated, committed evidence report. The comparison
logic is pure and is itself unit-tested hermetically; only `probe` touches the network.

Requires the optional `live` extra:  pip install -e ".[dev,live]"
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

REPORT_PATH = (
    Path(__file__).resolve().parents[1] / "docs/implementation/06-universe-verification.md"
)

AGREES = "agrees"
DISAGREES = "DISAGREES"
UNCORROBORATED = "uncorroborated"
CANDIDATE = "candidate"
REVIEW = "review"

#: Corporate-form suffixes carry no identifying information and differ between our
#: seed and the vendor's naming, so they are stripped before names are compared.
_NAME_NOISE = frozenset({"limited", "ltd", "inc", "incorporated", "corporation", "plc", "the"})


@dataclass(frozen=True, slots=True)
class VendorFacts:
    """What the vendor says about a symbol. Every field may be absent."""

    currency: str | None = None
    exchange: str | None = None
    quote_type: str | None = None
    long_name: str | None = None
    isin: str | None = None
    bar_count: int = 0


@dataclass(frozen=True, slots=True)
class Check:
    """One comparison between a seeded claim and the vendor's answer."""

    attribute: str
    status: str
    detail: str


def normalize_name(name: str) -> tuple[str, ...]:
    """Reduce a company name to comparable tokens (case, punctuation, form stripped)."""
    cleaned = "".join(character if character.isalnum() else " " for character in name.lower())
    return tuple(token for token in cleaned.split() if token not in _NAME_NOISE)


def names_agree(ours: str, theirs: str) -> bool:
    """Whether two names plausibly denote the same company.

    Prefix agreement rather than token overlap, deliberately: *Bajaj Finance* and
    *Bajaj Finserv* share a token and are different companies, which is precisely the
    confusion this milestone exists to catch.
    """
    a, b = normalize_name(ours), normalize_name(theirs)
    if not a or not b:
        return False
    shorter, longer = (a, b) if len(a) <= len(b) else (b, a)
    return longer[: len(shorter)] == shorter


def compare(reference, facts: VendorFacts, *, expected_mic: str | None) -> tuple[Check, ...]:
    """Compare one seeded instrument against the vendor's answers. Pure.

    `expected_mic` is the vendor's venue code already translated to a MIC by the
    adapter's symbology — the translation stays at L1, so this tool never learns the
    vendor's vocabulary.
    """
    from backend.domain.model.instruments import InstrumentType, isin_check_digit_valid

    checks: list[Check] = []

    # The tripwire for doc 05 finding 5: an unknown, renamed or delisted symbol returns
    # an empty payload rather than an error, so silence is the failure mode to name.
    if facts.bar_count > 0:
        checks.append(Check("price_history", AGREES, f"{facts.bar_count} bars returned"))
    else:
        checks.append(
            Check(
                "price_history",
                DISAGREES,
                "vendor returned NO bars — symbol may be wrong, renamed or delisted",
            )
        )

    if reference.currency is None:
        checks.append(
            Check(
                "currency",
                UNCORROBORATED,
                f"index levels are unitless points, so no currency is claimed "
                f"(vendor says {facts.currency or 'nothing'})",
            )
        )
    elif facts.currency is None:
        checks.append(Check("currency", UNCORROBORATED, "vendor reported no currency"))
    elif facts.currency.upper() == reference.currency.value:
        checks.append(Check("currency", AGREES, reference.currency.value))
    else:
        checks.append(
            Check(
                "currency",
                DISAGREES,
                f"ours {reference.currency.value} · vendor {facts.currency}",
            )
        )

    if facts.exchange is None:
        checks.append(Check("exchange", UNCORROBORATED, "vendor reported no exchange"))
    elif expected_mic is None:
        checks.append(
            Check(
                "exchange",
                UNCORROBORATED,
                f"vendor venue {facts.exchange!r} maps to no known MIC",
            )
        )
    elif expected_mic == reference.exchange:
        checks.append(Check("exchange", AGREES, f"{reference.exchange} (vendor {facts.exchange})"))
    else:
        checks.append(
            Check(
                "exchange",
                DISAGREES,
                f"ours {reference.exchange} · vendor {facts.exchange} → {expected_mic}",
            )
        )

    # `quoteType` separates INDEX from not-INDEX and nothing finer: an ETF reports
    # EQUITY (doc 05 finding 9), so ETF classification is our own knowledge (ED-017).
    vendor_is_index = (facts.quote_type or "").upper() == "INDEX"
    ours_is_index = reference.type is InstrumentType.INDEX
    if facts.quote_type is None:
        checks.append(Check("type", UNCORROBORATED, "vendor reported no quoteType"))
    elif ours_is_index != vendor_is_index:
        checks.append(
            Check("type", DISAGREES, f"ours {reference.type.value} · vendor {facts.quote_type}")
        )
    elif reference.type is InstrumentType.ETF:
        checks.append(
            Check(
                "type",
                UNCORROBORATED,
                f"vendor says {facts.quote_type}; it cannot distinguish ETF from equity, "
                "so ETF is our own canonical knowledge",
            )
        )
    else:
        checks.append(Check("type", AGREES, f"{reference.type.value} (vendor {facts.quote_type})"))

    if facts.long_name is None:
        checks.append(Check("name", UNCORROBORATED, "vendor reported no name"))
    elif names_agree(reference.name, facts.long_name):
        checks.append(Check("name", AGREES, facts.long_name))
    else:
        checks.append(
            Check("name", REVIEW, f"ours {reference.name!r} · vendor {facts.long_name!r}")
        )

    vendor_isin = facts.isin if facts.isin and isin_check_digit_valid(facts.isin) else None
    if reference.isin is None and vendor_isin is None:
        checks.append(
            Check(
                "isin",
                UNCORROBORATED,
                f"not claimed by us; vendor offers {facts.isin!r} which is not a valid ISIN"
                if facts.isin
                else "not claimed by us; vendor reported none",
            )
        )
    elif reference.isin is None:
        checks.append(
            Check(
                "isin",
                CANDIDATE,
                f"vendor offers {vendor_isin} — confirm against an authoritative "
                "source before seeding",
            )
        )
    elif vendor_isin is None:
        checks.append(
            Check(
                "isin",
                UNCORROBORATED,
                f"we claim {reference.isin}; vendor offers nothing valid",
            )
        )
    elif vendor_isin == reference.isin:
        checks.append(Check("isin", AGREES, reference.isin))
    else:
        checks.append(Check("isin", DISAGREES, f"ours {reference.isin} · vendor {vendor_isin}"))

    return tuple(checks)


def verdict(checks: tuple[Check, ...]) -> str:
    """The row-level outcome: any disagreement fails; a soft name mismatch asks."""
    if any(check.status == DISAGREES for check in checks):
        return "FAILED"
    if any(check.status == REVIEW for check in checks):
        return "REVIEW"
    return "OK"


def probe(symbol: str) -> VendorFacts:
    """Ask the vendor about `symbol`. The only impure function in this module."""
    import yfinance  # noqa: PLC0415  (lazy: the hermetic tests need neither this nor pandas)

    ticker = yfinance.Ticker(symbol)
    try:
        info = dict(ticker.info)
    except Exception:  # noqa: BLE001 - an absent symbol must be reported, not raised
        info = {}
    try:
        history = ticker.history(period="5d")
        bar_count = 0 if history is None else len(history)
    except Exception:  # noqa: BLE001
        bar_count = 0
    # ISIN is a separate `Ticker` property, NOT a key in `.info` — reading it from the
    # info dict yields None for every symbol, which would render every ISIN check
    # "uncorroborated" and the whole check vacuous. Caught only because a run that
    # verified nothing still reported OK for all twenty rows; a green report is not
    # evidence unless you know which questions were actually asked.
    try:
        isin = ticker.isin
    except Exception:  # noqa: BLE001
        isin = None

    return VendorFacts(
        currency=info.get("currency"),
        exchange=info.get("exchange"),
        quote_type=info.get("quoteType"),
        long_name=info.get("longName") or info.get("shortName"),
        isin=isin,
        bar_count=bar_count,
    )


def render_report(rows: list[tuple[str, str, str, tuple[Check, ...]]], probed_at: datetime) -> str:
    """Render the evidence report. `rows` are (instrument_id, symbol, verdict, checks)."""
    counts = {"OK": 0, "REVIEW": 0, "FAILED": 0}
    for _, _, row_verdict, _ in rows:
        counts[row_verdict] += 1

    lines = [
        "# Implementation · 06 · Universe Identity Verification",
        "",
        "| | |",
        "|---|---|",
        "| **Status** | Evidence — regenerate, do not hand-edit |",
        "| **Produced by** | `python -m tools.verify_universe` (live provider, never CI) |",
        f"| **Probed** | {probed_at.isoformat()} |",
        f"| **Result** | {counts['OK']} ok · {counts['REVIEW']} review · "
        f"{counts['FAILED']} failed |",
        "",
        "Every expectation below comes from the committed seed; the vendor supplies only",
        "the answers. `uncorroborated` is a real outcome, not a soft pass — it records",
        "exactly what this provider cannot vouch for.",
        "",
    ]
    for instrument_id, symbol, row_verdict, checks in rows:
        lines.append(f"## {instrument_id} · `{symbol}` — **{row_verdict}**")
        lines.append("")
        lines.append("| attribute | status | detail |")
        lines.append("|---|---|---|")
        for check in checks:
            lines.append(f"| {check.attribute} | {check.status} | {check.detail} |")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--instrument", default=None, help="verify one instrument id")
    parser.add_argument("--out", type=Path, default=REPORT_PATH, help="report path")
    args = parser.parse_args(argv)

    from backend.domain.model.instruments import known_instruments
    from backend.providers.yfinance.symbology import mic_for_vendor_exchange, to_vendor_symbol

    references = [
        reference
        for reference in known_instruments()
        if args.instrument is None or reference.instrument_id.value == args.instrument
    ]
    if not references:
        print(f"no seeded instrument named {args.instrument!r}", file=sys.stderr)
        return 1

    rows: list[tuple[str, str, str, tuple[Check, ...]]] = []
    for reference in references:
        symbol = to_vendor_symbol(reference.instrument_id)
        try:
            facts = probe(symbol)
        except Exception as exc:  # noqa: BLE001 - a tool reports, it does not raise at a user
            print(f"probe failed for {symbol}: {type(exc).__name__}: {exc}", file=sys.stderr)
            return 1
        expected_mic = mic_for_vendor_exchange(facts.exchange) if facts.exchange else None
        checks = compare(reference, facts, expected_mic=expected_mic)
        row_verdict = verdict(checks)
        rows.append((reference.instrument_id.value, symbol, row_verdict, checks))
        print(f"{row_verdict:<7} {reference.instrument_id.value:<22} {symbol}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_report(rows, datetime.now(UTC)) + "\n")
    print(f"\nwrote {args.out}")
    return 1 if any(row[2] == "FAILED" for row in rows) else 0


if __name__ == "__main__":  # pragma: no cover - developer entry point
    sys.exit(main())
